gcd_iter: gcd_iter.o main_iter.o 
gcd_euclid: gcd_euclid.o main_euclid.o
gcd_recursive: gcd_recursive.o main_recursive.o
linked_list: linked_list.o main_linked_list.o
queue: queue.o main_queue.o
doublylinked_list: doublylinked_list.o main_doublylinked_list.o
open_addressing: open_addressing.o main_open_addressing.o
linear_probing: linear_probing.o main_linear_probing.o
double_hashing: double_hashing.o main_double_hashing.o
binarytree: binarytree.o main_binarytree.o
binarysearchtree: binarysearchtree.o main_binarysearchtree.o
bst_advanced: bst_advanced.o main_bst_advanced.o
sort_collection: sort_collection.o main_sort_collection.o
main_dijkstra: dijkstra.o main_dijkstra.o
main_floyd: floyd.o main_floyd.o
mainNaive: cmp.o naive.o readFile.o
testcompnext: cmp.o compnext.o readFile.o
mainkmp: cmp.o kmp.o compnext.o readFile.o
knapsack: knapsack.o
knapsackDP: knapsackDP.o
knapsackDP2: knapsackDP2.o
subsetsum: subsetsum.o